# Generated by Django 5.2.9 on 2026-01-02 14:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devtools', '0003_alter_devtool_kind_alter_devtool_name'),
        ('ideas', '0002_remove_ideastar_unique_user_idea_star_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='idea',
            name='devtool',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ideas', to='devtools.devtool'),
        ),
    ]
