# Generated by Django 5.2.9 on 2026-01-02 17:49

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devtools', '0004_alter_devtool_kind_alter_devtool_name'),
        ('ideas', '0003_alter_idea_devtool'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='idea',
            name='created_at',
        ),
        migrations.AlterField(
            model_name='idea',
            name='devtool',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='devtools.devtool'),
        ),
        migrations.AlterField(
            model_name='idea',
            name='image',
            field=models.ImageField(blank=True, upload_to='ideas/'),
        ),
        migrations.AlterField(
            model_name='idea',
            name='interest',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AlterField(
            model_name='idea',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
