# Generated by Django 5.2.9 on 2026-01-02 17:52

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devtools', '0004_alter_devtool_kind_alter_devtool_name'),
        ('ideas', '0004_remove_idea_created_at_alter_idea_devtool_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='idea',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='idea',
            name='devtool',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ideas', to='devtools.devtool'),
        ),
        migrations.AlterField(
            model_name='idea',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='ideas/'),
        ),
        migrations.AlterField(
            model_name='idea',
            name='interest',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='idea',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
