# Generated by Django 5.2.9 on 2026-01-02 17:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ideas', '0005_idea_created_at_alter_idea_devtool_alter_idea_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='idea',
            name='interest',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)]),
        ),
    ]
