# Generated by Django 5.2.9 on 2025-12-31 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='제목')),
                ('year', models.PositiveIntegerField(verbose_name='개봉년도')),
                ('genre', models.CharField(choices=[('action', '액션'), ('drama', '드라마'), ('comedy', '코미디'), ('thriller', '스릴러'), ('romance', '로맨스'), ('sf', 'SF'), ('horror', '호러'), ('animation', '애니메이션'), ('etc', '기타')], max_length=20, verbose_name='장르')),
                ('rating', models.DecimalField(choices=[(1.0, '1'), (1.5, '1.5'), (2.0, '2'), (2.5, '2.5'), (3.0, '3'), (3.5, '3.5'), (4.0, '4'), (4.5, '4.5'), (5.0, '5')], decimal_places=1, max_digits=2, verbose_name='별점')),
                ('runtime', models.PositiveIntegerField(verbose_name='러닝타임(분)')),
                ('content', models.TextField(verbose_name='리뷰')),
                ('director', models.CharField(max_length=100, verbose_name='감독')),
                ('actors', models.CharField(max_length=200, verbose_name='배우')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
            ],
        ),
    ]
