# Generated by Django 5.2.9 on 2026-01-02 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devtools', '0002_alter_devtool_kind_alter_devtool_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devtool',
            name='kind',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='devtool',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
