# Generated by Django 5.2.9 on 2026-01-02 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devtools', '0003_alter_devtool_kind_alter_devtool_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devtool',
            name='kind',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='devtool',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
